# Generated by Django 5.0.6 on 2024-07-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(default='ce251614', max_length=8, unique=True),
        ),
    ]
