# Generated by Django 5.0.4 on 2024-07-15 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BROKERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_SYMBOL_QTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('SYMBOL', models.CharField(blank=True, max_length=50, null=True)),
                ('QUANTITY', models.IntegerField(blank=True, null=True)),
                ('Order_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Strategy', models.CharField(blank=True, max_length=50, null=True)),
                ('trade', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP', models.CharField(max_length=20)),
                ('min_quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_token', models.CharField(max_length=20)),
                ('tradingsymbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('expiry', models.CharField(blank=True, max_length=20, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('tick_size', models.FloatField()),
                ('lot_size', models.IntegerField()),
                ('instrument_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAngelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clint', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('symboltoken', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('segment_type', models.CharField(max_length=20)),
                ('squareoff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoploss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strategy', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SYMBOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(max_length=50)),
                ('SYMBOL_order', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol_token', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lotsize', models.IntegerField(blank=True, null=True)),
                ('instrumenttype', models.CharField(blank=True, max_length=20, null=True)),
                ('exch_seg', models.CharField(blank=True, max_length=10, null=True)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('Long_Entry', 'Long Entry'), ('Long_Exit', 'Long Exit'), ('Short_Entry', 'Short Entry'), ('Short_Exit', 'Short Exit')], max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ind_clientDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clint_id', models.CharField(default='d53846c8', max_length=8, unique=True)),
                ('clint_name_first', models.CharField(blank=True, max_length=50, null=True)),
                ('clint_name_last', models.CharField(blank=True, max_length=50, null=True)),
                ('clint_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clint_password', models.CharField(blank=True, max_length=50, null=True)),
                ('clint_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('clint_verify_code', models.CharField(blank=True, max_length=15, null=True)),
                ('clint_date_joined', models.DateTimeField(default=None, verbose_name='date joined')),
                ('clint_last_login', models.DateTimeField(default=None, verbose_name='last login')),
                ('clint_is_staff', models.BooleanField(default=False)),
                ('clint_status', models.CharField(blank=True, max_length=15, null=True)),
                ('clint_plane', models.CharField(blank=True, max_length=15, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=355, null=True)),
                ('feed_token', models.CharField(blank=True, max_length=355, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=355, null=True)),
                ('sub_admin_id', models.CharField(blank=True, max_length=50, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.brokers')),
                ('client_Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group')),
            ],
        ),
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ind_clientdt', to_field='clint_id')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='symbols',
            field=models.ManyToManyField(related_name='groups', to='accounts.symbol'),
        ),
        migrations.CreateModel(
            name='ClientSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.CharField(blank=True, max_length=50, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ids', models.CharField(blank=True, max_length=50, null=True)),
                ('ENTRY', models.CharField(blank=True, max_length=50, null=True)),
                ('TYPE', models.CharField(choices=[('BUY_ENTRY', 'BUY_ENTRY'), ('BUY_EXIT', 'BUY_EXIT'), ('SELL_ENTRY', 'SELL_ENTRY'), ('SELL_EXIT', 'SELL_EXIT')], max_length=10)),
                ('QUANTITY', models.FloatField(blank=True, null=True)),
                ('ENTRY_PRICE', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('EXIT_PRICE', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cumulative_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_order_id', models.CharField(blank=True, max_length=90, null=True)),
                ('SYMBOL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_signals', to='accounts.symbol')),
            ],
        ),
    ]
