# Generated by Django 5.0.6 on 2024-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trade_quantity_trade_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='status',
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='aa9bb2f7', max_length=8, unique=True),
        ),
    ]
