# Generated by Django 5.0.4 on 2024-07-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trade_lot_size_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='1e2362b2', max_length=8, unique=True),
        ),
    ]
