# Generated by Django 5.0.4 on 2024-07-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='lot_size',
        ),
        migrations.AddField(
            model_name='trade',
            name='clint_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='1f97c8ea', max_length=8, unique=True),
        ),
    ]
