# Generated by Django 5.0.6 on 2024-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notification_alter_ind_clientdt_clint_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='7f528dbd', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='clint_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
