# Generated by Django 5.0.6 on 2024-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ind_clientdt_clint_id_alter_trade_clint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='97422205', max_length=8, unique=True),
        ),
    ]
