# Generated by Django 5.0.4 on 2024-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_ind_clientdt_ip_address_ind_clientdt_login_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='56d2a56a', max_length=8, unique=True),
        ),
    ]
