# Generated by Django 5.0.6 on 2024-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_clientdt',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ind_clientdt',
            name='telegram_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='b52996d2', max_length=8, unique=True),
        ),
    ]
