# Generated by Django 5.0.6 on 2024-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_ind_clientdt_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='d360c07a', max_length=8, unique=True),
        ),
    ]
