# Generated by Django 5.0.6 on 2024-07-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ind_clientdt',
            name='Term_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='6b8ae5aa', max_length=8, unique=True),
        ),
    ]
