# Generated by Django 5.0.4 on 2024-08-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_clientstatus_alter_ind_clientdt_clint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('live', 'Live')], default='demo', max_length=10),
        ),
        migrations.AlterField(
            model_name='ind_clientdt',
            name='clint_id',
            field=models.CharField(default='17768f35', max_length=8, unique=True),
        ),
    ]
